databases:
  - name: eyeopener
    databaseName: eyeopener
    user: sari

services:
  - type: web
    name: eye-opener
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ./eyeopener.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eyeopener
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4